services:
  bankwebapp:
    image: bankwebapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:80"
        - "9090:443"
    depends_on:
        - bankdb
    restart: always
    volumes:
      - BankWebAppKeys:/root/.aspnet/DataProtection-Keys
    healthcheck:
      test: curl -sS http://localhost:80/api/healthcheck/all | jq -e '.OverallStatusInt == 2'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 1m
      
  bankdb:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: BankDB
    ports:
      - "6661:1433"
    environment:
        - ACCEPT_EULA=1
        - MSSQL_SA_PASSWORD=Heslo1234.
    cap_add:
      - SYS_PTRACE
    restart: always
    volumes:
      - ./BankDB-data:/var/opt/mssql/data
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Heslo1234. -Q "SELECT 1" || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 1m
  
  #bankdb:
  #  image: mcr.microsoft.com/azure-sql-edge
  #  container_name: BankDB
  #  ports:
  #    - "6661:1433"
  #  environment:
  #    - ACCEPT_EULA=1
  #    - MSSQL_SA_PASSWORD=Heslo1234.
  #  cap_add:
  #    - SYS_PTRACE
  #  restart: always
  #  volumes:
  #    - BankDB:/var/opt/mssql

volumes: 
    BankWebAppKeys:
